# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

assetic:
    bundles:
        - CampaignChainSecurityAuthenticationServerOAuthBundle

fos_oauth_server:
    db_driver:           orm
    client_class:        CampaignChain\Security\Authentication\Server\OAuthBundle\Entity\Client
    access_token_class:  CampaignChain\Security\Authentication\Server\OAuthBundle\Entity\AccessToken
    refresh_token_class: CampaignChain\Security\Authentication\Server\OAuthBundle\Entity\RefreshToken
    auth_code_class:     CampaignChain\Security\Authentication\Server\OAuthBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager
        options:
            # Changing tokens and authcode lifetime
            access_token_lifetime: 3600
            refresh_token_lifetime: 1209600
            auth_code_lifetime: 30